#ifndef _CLIMB_SYSTEM_MAP_HG_
#define _CLIMB_SYSTEM_MAP_HG_

const int CLIMBSYSTEM_MOTOR_ID = 10;
const int CLIMBSYSTEM_SOLENOID_CAN_ID = 8;
const int CLIMBSYSTEM_SOLENOID_FORWARD_CHANNEL_ID = 0;

#endif
